'use strict';
const metricCatalog=[{"id": 1, "title": "Disponibilité des machines", "unit": "bool", "group": "cpu"}, {"id": 2, "title": "Cœurs logiques disponibles", "unit": "short", "group": "cpu"}, {"id": 3, "title": "CPU · utilisation", "unit": "percent", "group": "cpu"}, {"id": 4, "title": "RAM · utilisée / capacité", "unit": "percent", "group": "memory"}, {"id": 5, "title": "CPU · par cœur", "unit": "percent", "group": "cpu"}, {"id": 6, "title": "Charge système", "unit": "short", "group": "cpu"}, {"id": 7, "title": "RAM disponible", "unit": "bytes", "group": "memory"}, {"id": 8, "title": "Swap utilisée", "unit": "bytes", "group": "memory"}, {"id": 9, "title": "Volumes · espace utilisé", "unit": "percent", "group": "storage"}, {"id": 10, "title": "Volumes · espace disponible", "unit": "bytes", "group": "storage"}, {"id": 11, "title": "Volumes · inodes utilisés", "unit": "percent", "group": "storage"}, {"id": 12, "title": "Stockage · croissance horaire", "unit": "bytes", "group": "storage"}, {"id": 13, "title": "Réseau · réception", "unit": "Bps", "group": "network"}, {"id": 14, "title": "Réseau · émission", "unit": "Bps", "group": "network"}, {"id": 15, "title": "Réseau · erreurs reçues par seconde", "unit": "ops", "group": "network"}, {"id": 16, "title": "Réseau · paquets perdus par seconde", "unit": "pps", "group": "network"}, {"id": 17, "title": "Disques · lecture", "unit": "Bps", "group": "storage"}, {"id": 18, "title": "Disques · écriture", "unit": "Bps", "group": "storage"}, {"id": 19, "title": "Disques · occupation E/S", "unit": "percent", "group": "storage"}, {"id": 20, "title": "Nombre de processus", "unit": "short", "group": "system"}, {"id": 21, "title": "Températures", "unit": "celsius", "group": "sensors"}, {"id": 22, "title": "Temps depuis démarrage", "unit": "s", "group": "system"}, {"id": 23, "title": "GPU · utilisation", "unit": "percent", "group": "sensors"}, {"id": 24, "title": "GPU · consommation mesurée", "unit": "watt", "group": "sensors"}, {"id": 25, "title": "Alertes actives", "unit": "short", "group": "system"}, {"id": 26, "title": "Collecte · ancienneté", "unit": "s", "group": "system"}];
const metricGroups={cpu:'Processeurs',memory:'Mémoire',storage:'Stockage',network:'Réseau',sensors:'Capteurs & GPU',system:'Système',all:'Tout'};
const metricColors=['var(--cyan)','var(--purple)','var(--blue)','var(--orange)','var(--green)','var(--red)'];
let analysisGroup='cpu',analysisEpoch=0,analysisCustom=null,analysisResults=new Map(),analysisHidden=new Map(),analysisContext='',analysisPending=false;
const metricFormat=(v,u)=>!Number.isFinite(v)?'—':u==='bool'?(v>=.5?'En ligne':'Hors ligne'):u==='bytes'?bytes(v):u==='Bps'?bytes(v,true):u==='percent'?pct(v):u==='s'?uptime(v):num(v,2)+(u==='celsius'?' °C':u==='watt'?' W':u==='pps'?' paquets/s':u==='ops'?' /s':'');
function metricLabel(labels){return Object.entries(labels).filter(([k])=>!['__name__','job','instance','project','ops_project'].includes(k)).map(([k,v])=>k==='host'?(names[v]?.[0]||v):k==='core'?'Cœur '+v:k==='minutes'?v+' min':v).join(' · ')||'Mesure';}
function analysisBounds(){const end=Math.floor(Date.now()/1000);return analysisCustom||{start:end-({'15m':900,'1h':3600,'24h':86400,'7d':604800,'30d':2592000,'1y':31536000,all:Math.min(31536000,Math.max(900,end-(data?.archive?.oldest_summary||end-3600)))}[period]||3600),end};}
function analysisDate(t){const d=new Date(t*1000);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16);}
function metricCard(p){return `<article class="metric-card" data-metric="${p.id}"><div class="metric-heading"><div><span class="metric-family">${opsIcon(groupIcon(p.group))}${esc(metricGroups[p.group])}</span><h3>${esc(p.title)}</h3></div><div><button class="metric-expand" data-expand="${p.id}" aria-label="Agrandir ${esc(p.title)}" aria-expanded="false">${opsIcon('maximize-2')}</button><button data-metric-export="${p.id}" class="metric-export" aria-label="Exporter ${esc(p.title)} en CSV" disabled>${opsIcon('download')}<span>CSV</span></button></div></div><div class="metric-plot chart" id="metric-plot-${p.id}"><div class="chart-empty">Chargement des mesures…</div></div><div class="metric-inspector" id="metric-inspector-${p.id}" aria-live="off">Survolez le graphique pour lire les valeurs.</div><div id="metric-legend-${p.id}" class="metric-legend"></div></article>`;}
function renderMetric(p,result){
 const el=$('#metric-plot-'+p.id);if(!el)return;
 const disabled=analysisHidden.get(p.id)||new Set();
 const all=result.series.map((s,i)=>({...s,index:i,label:metricLabel(s.labels),points:s.values.map(([t,v])=>[Number(t),Number(v)]).filter(([t,v])=>Number.isFinite(t)&&Number.isFinite(v))}));
 const shown=all.filter(s=>!disabled.has(s.label));const values=shown.flatMap(s=>s.points.map(x=>x[1]));
 const legend=$('#metric-legend-'+p.id);
 legend.innerHTML=all.length?'<div class="metric-legend-head"><span>Série</span><span>Dernière</span><span>Min.</span><span>Max.</span><span>Moy.</span></div>'+all.map(s=>{const v=s.points.map(x=>x[1]),stats=v.length?[v[v.length-1],Math.min(...v),Math.max(...v),v.reduce((a,b)=>a+b,0)/v.length]:[NaN,NaN,NaN,NaN];return `<button class="metric-series ${disabled.has(s.label)?'muted-series':''}" data-metric-toggle="${p.id}" data-series="${s.index}" aria-pressed="${!disabled.has(s.label)}"><span><i style="background:${metricColors[s.index%metricColors.length]}"></i>${esc(s.label)}</span>${stats.map(n=>`<span>${esc(metricFormat(n,p.unit))}</span>`).join('')}</button>`;}).join(''):'';
 $(`[data-metric-export="${p.id}"]`).disabled=!all.length;
 if(!values.length){el.innerHTML=`<div class="chart-empty"><b>${all.length?'Séries masquées':'Aucune mesure disponible'}</b><span>${all.length?'Réactivez une série dans la légende.':p.group==='sensors'?'Ce capteur peut ne pas être exposé par la machine.':'Aucun relevé détaillé pour cette sélection.'}</span></div>`;$('#metric-inspector-'+p.id).textContent='';return;}
 const w=640,h=225,left=66,right=12,top=14,bottom=28;
 let min=Math.min(0,...values),max=Math.max(...values);max=max===min?min+1:max+(max-min)*.12;
 if(p.unit==='percent'&&min>=0&&max<100)max=100;
 if(p.unit==='bool'){min=0;max=1;}
 const x=t=>left+(t-result.start)/(result.end-result.start)*(w-left-right),y=v=>top+(max-v)/(max-min)*(h-top-bottom);
 let svg=`<svg viewBox="0 0 ${w} ${h}" role="img" tabindex="0" aria-label="${esc(p.title)}. Utilisez les flèches pour inspecter les valeurs.">`;
 for(let i=0,n=p.unit==='bool'?2:4;i<n;i++){const v=min+(max-min)*i/(n-1);svg+=`<line class="grid" x1="${left}" x2="${w-right}" y1="${y(v)}" y2="${y(v)}"/><text x="${left-7}" y="${y(v)+4}" text-anchor="end">${esc(metricFormat(v,p.unit))}</text>`;}
 for(const s of shown){let path='',previous=null;for(const [t,v] of s.points){path+=(previous!==null&&t-previous<=result.step*1.8?'L':'M')+x(t).toFixed(2)+','+y(v).toFixed(2)+' ';previous=t;}svg+=`<path d="${path}" fill="none" stroke="${metricColors[s.index%metricColors.length]}" stroke-width="2" vector-effect="non-scaling-stroke"/>`;if(s.points.length===1){const[t,v]=s.points[0];svg+=`<circle cx="${x(t)}" cy="${y(v)}" r="3" fill="${metricColors[s.index%metricColors.length]}"/>`;}}
 for(const [t,anchor] of [[result.start,'start'],[(result.start+result.end)/2,'middle'],[result.end,'end']]){const d=new Date(t*1000);svg+=`<text x="${x(t)}" y="${h-3}" text-anchor="${anchor}">${esc(result.end-result.start>86400?d.toLocaleDateString('fr-CH',{day:'2-digit',month:'2-digit'}):d.toLocaleTimeString('fr-CH',{hour:'2-digit',minute:'2-digit'}))}</text>`;}
 svg+='<line class="metric-cursor" stroke="var(--muted)" stroke-dasharray="3 4" y1="14" y2="197" visibility="hidden"/></svg>';el.innerHTML=svg;
 const graphic=el.querySelector('svg');let fraction=1;
 function inspect(f){fraction=Math.max(0,Math.min(1,f));const t=result.start+fraction*(result.end-result.start),cursor=graphic.querySelector('.metric-cursor');cursor.setAttribute('x1',x(t));cursor.setAttribute('x2',x(t));cursor.setAttribute('visibility','visible');const entries=shown.map(s=>{const nearest=s.points.reduce((best,q)=>!best||Math.abs(q[0]-t)<Math.abs(best[0]-t)?q:best,null);return `${s.label} : ${nearest&&Math.abs(nearest[0]-t)<=result.step*1.5?metricFormat(nearest[1],p.unit):'—'}`;});$('#metric-inspector-'+p.id).textContent=new Date(t*1000).toLocaleString('fr-CH')+' · '+entries.join(' · ');}
 graphic.addEventListener('pointermove',e=>{const r=graphic.getBoundingClientRect();inspect(((e.clientX-r.left)/r.width*w-left)/(w-left-right));});
 graphic.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();inspect(e.key==='Home'?0:e.key==='End'?1:fraction+(e.key==='ArrowRight'?1:-1)/240);}});
 if(result.truncated)$('#metric-inspector-'+p.id).textContent='128 séries affichées : choisissez une machine pour affiner.';
}
async function loadAnalysis(force=false){
 if(document.hidden||document.body.classList.contains('logs-view')||historical)return;
 const context=[selected,period,analysisGroup,JSON.stringify(analysisCustom)].join('|');
 if(analysisPending&&!force&&context===analysisContext)return;
 const epoch=++analysisEpoch;analysisContext=context;analysisPending=true;const bounds=analysisBounds(),host=selected;
 if(!analysisCustom){$('#analysis-from').value=analysisDate(bounds.start);$('#analysis-to').value=analysisDate(bounds.end);}
 const panels=metricCatalog.filter(p=>analysisGroup==='all'||p.group===analysisGroup).sort((a,b)=>((a.id===1||a.id===2)?100+a.id:a.id)-((b.id===1||b.id===2)?100+b.id:b.id));
 const rebuild=$('#analysis-grid').dataset.context!==context;
 if(rebuild){$('#analysis-grid').innerHTML=panels.map(metricCard).join('');$('#analysis-grid').dataset.context=context;}
 $('#analysis-range').textContent=(names[host]?.[0]||'Toutes les machines')+' · '+new Date(bounds.start*1000).toLocaleString('fr-CH')+' → '+new Date(bounds.end*1000).toLocaleString('fr-CH')+(analysisCustom?' · période fixe':' · suivi du direct');
 $('#analysis-status').textContent='Chargement…';let index=0,ok=0,failed=0;
 async function worker(){while(index<panels.length&&epoch===analysisEpoch){const p=panels[index++];try{const result=await window.__TAURI__.core.invoke('infrastructure_series',{metric:p.id,host,...bounds});if(epoch!==analysisEpoch)return;analysisResults.set(p.id,result);renderMetric(p,result);ok++;}catch(e){if(epoch!==analysisEpoch)return;failed++;analysisResults.delete(p.id);$('#metric-plot-'+p.id).innerHTML=`<div class="chart-empty"><b>Mesures indisponibles</b><span>${esc(e)}</span></div>`;$('#metric-legend-'+p.id).innerHTML='';$('#metric-inspector-'+p.id).textContent='';$(`[data-metric-export="${p.id}"]`).disabled=true;}}}
 await Promise.all([worker(),worker(),worker()]);if(epoch!==analysisEpoch)return;analysisPending=false;$('#analysis-status').textContent=`${ok}/${panels.length} graphiques chargés${failed?' · '+failed+' indisponibles':''}`;
}
$('#metric-categories').innerHTML=Object.entries(metricGroups).map(([key,label])=>`<button data-metric-group="${key}" class="${key===analysisGroup?'active':''}" aria-pressed="${key===analysisGroup}">${opsIcon(groupIcon(key))}<span>${label}</span></button>`).join('');
document.addEventListener('click',e=>{
 const group=e.target.closest('[data-metric-group]');if(group){analysisGroup=group.dataset.metricGroup;document.querySelectorAll('[data-metric-group]').forEach(b=>{b.classList.toggle('active',b===group);b.setAttribute('aria-pressed',String(b===group));});loadAnalysis(true);}
 const expand=e.target.closest('[data-expand]');if(expand){const card=expand.closest('.metric-card');card.classList.toggle('expanded');expand.setAttribute('aria-expanded',String(card.classList.contains('expanded')));}
 const toggle=e.target.closest('[data-metric-toggle]');if(toggle){const id=Number(toggle.dataset.metricToggle),r=analysisResults.get(id);if(!r)return;const label=metricLabel(r.series[Number(toggle.dataset.series)].labels),hidden=analysisHidden.get(id)||new Set();hidden.has(label)?hidden.delete(label):hidden.add(label);analysisHidden.set(id,hidden);renderMetric(metricCatalog.find(p=>p.id===id),r);}
 if(e.target.closest('[data-host],[data-period],#refresh,#history-live,[data-infra-view="resources"]')){if(e.target.closest('[data-period]'))analysisCustom=null;loadAnalysis(true);}
 const exportButton=e.target.closest('[data-metric-export]');if(exportButton)exportMetric(Number(exportButton.dataset.metricExport));
});
$('#analysis-apply').addEventListener('click',()=>{const start=Math.floor(new Date($('#analysis-from').value).getTime()/1000),end=Math.floor(new Date($('#analysis-to').value).getTime()/1000);if(!Number.isFinite(start)||!Number.isFinite(end)||start<=0||end<=start||end-start>366*86400||end>Date.now()/1000+60){$('#analysis-status').textContent='Choisissez une période passée valide, de moins d’un an.';return;}analysisCustom={start,end};loadAnalysis(true);});
$('#analysis-live').addEventListener('click',()=>{analysisCustom=null;loadAnalysis(true);});
async function exportMetric(id){const result=analysisResults.get(id);if(!result)return;try{const path=await window.__TAURI__.core.invoke('infrastructure_export_series',{payload:result});$('#analysis-status').textContent='Export enregistré : '+path;}catch(e){$('#analysis-status').textContent=String(e);}}
setInterval(()=>{if(!analysisCustom)loadAnalysis();},30000);loadAnalysis();
document.addEventListener('visibilitychange',()=>{if(!document.hidden)loadAnalysis(true);});
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.closest('tr[data-host]'))loadAnalysis(true);});
