'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={'dell-control':['Dell','Poste de contrôle'],'edge-vps':['VPS','Passerelle publique'],prod:['Production','Applications'],nas:['NAS','Stockage et services'],gamebox:['Gamebox','Jeux et applications']};
let data=null,selected='all',period='1h',busy=false,historical=null;
const valid=n=>typeof n==='number'&&Number.isFinite(n), num=(n,d=1)=>valid(n)?n.toLocaleString('fr-CH',{maximumFractionDigits:d}):'—', pct=n=>valid(n)?num(n)+' %':'—';
function bytes(n,rate=false){if(!valid(n))return '—';let i=0;const units=rate?['o/s','Kio/s','Mio/s','Gio/s']:['o','Kio','Mio','Gio','Tio','Pio'];while(n>=1024&&i<units.length-1){n/=1024;i++;}return num(n,n>=100?0:1)+' '+units[i];}
const ratio=(n,d)=>valid(n)&&valid(d)&&d>0?n/d*100:null;
const fresh=h=>h.status==='online'&&valid(h.received_at)&&Date.now()/1000-h.received_at<50;
function hosts(){return Object.entries(names).map(([id,[label,role]])=>data?.hosts.find(h=>h.id===id)||{id,label,role,status:'waiting',metrics:null,history:{}});}
function uptime(n){if(!valid(n))return '—';if(n>=86400)return num(Math.floor(n/86400),0)+' j '+Math.floor(n%86400/3600)+' h';return Math.floor(n/3600)+' h '+Math.floor(n%3600/60)+' min';}
function meter(n,color='var(--cyan)'){return `<div class="meter" style="--accent:${color}"><i style="width:${valid(n)?Math.max(0,Math.min(100,n)):0}%"></i></div>`;}
function sum(items,key){const values=items.map(x=>x[key]);return values.length&&values.every(valid)?values.reduce((a,b)=>a+b,0):null;}
function point(h){const m=h.metrics;if(!m)return {};const net=m.network.filter(n=>n.physical);return {cpu:m.cpu.usage_pct,cores:m.cpu.cores,memory_used:m.memory.used_bytes,memory_total:m.memory.total_bytes,storage_used:sum(m.filesystems,'used_bytes'),storage_total:sum(m.filesystems,'total_bytes'),rx:sum(net,'rx_bytes_per_second'),tx:sum(net,'tx_bytes_per_second'),read:sum(m.disk_io.filter(d=>!d.name.startsWith('dm-')&&!d.name.startsWith('md')),'read_bytes_per_second'),write:sum(m.disk_io.filter(d=>!d.name.startsWith('dm-')&&!d.name.startsWith('md')),'write_bytes_per_second'),processes:m.process_count};}
function aggregate(points){const r={};for(const k of ['cores','memory_used','memory_total','storage_used','storage_total','rx','tx','read','write','processes'])r[k]=sum(points,k);r.cpu=points.length&&points.every(p=>valid(p.cpu)&&valid(p.cores))?points.reduce((a,p)=>a+p.cpu*p.cores,0)/r.cores:null;return r;}
function current(){return selected==='all'?aggregate(hosts().filter(fresh).map(point)):point(hosts().find(h=>h.id===selected));}
function history(){if(selected!=='all')return hosts().find(h=>h.id===selected)?.history?.[period]||[];const rows=new Map();for(const h of hosts())for(const p of h.history?.[period]||[]){const t=Math.floor(p.t/60)*60;if(!rows.has(t))rows.set(t,new Map());rows.get(t).set(h.id,p);}return [...rows].sort((a,b)=>a[0]-b[0]).map(([t,group])=>({t,...(group.size===5?aggregate([...group.values()]):{cpu:null,memory_used:null,memory_total:null,rx:null,tx:null,read:null,write:null})}));}
function chart(selector,rows,series,format,ceiling){const el=$(selector), usable=rows.filter(r=>series.some(s=>valid(s.value(r))));if(usable.length<2){el.innerHTML='<div class="chart-empty"><b>Premières mesures en cours</b><span>L’historique se construit au fil des collectes.</span></div>';return;}const w=480,h=154,left=48,right=14,top=12,bottom=26,t0=rows[0].t,t1=rows[rows.length-1].t,max=ceiling||Math.max(1,...usable.flatMap(r=>series.map(s=>s.value(r)).filter(valid)))*1.15;const x=t=>left+(t-t0)/(t1-t0||1)*(w-left-right),y=v=>top+(1-Math.min(v,max)/max)*(h-top-bottom);let svg=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(el.parentElement.querySelector('h2').textContent)} : historique ${esc(period)}">`;
for(let i=0;i<4;i++){const value=max*i/3,yy=y(value);svg+=`<line class="grid" x1="${left}" y1="${yy}" x2="${w-right}" y2="${yy}"/><text x="${left-8}" y="${yy+3}" text-anchor="end">${esc(format(value))}</text>`;}
const expected=Math.max(180,...rows.map(r=>(r.bucket_seconds||60)*1.5));for(const s of series){let path='',prev=null;for(const r of rows){const v=s.value(r);if(!valid(v)){prev=null;continue;}path+=`${prev&&r.t-prev.t<expected?'L':'M'}${x(r.t).toFixed(2)},${y(v).toFixed(2)} `;prev=r;}svg+=`<path d="${path}" fill="none" stroke="${s.color}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>`;for(const r of usable){const v=s.value(r);if(valid(v))svg+=`<circle cx="${x(r.t)}" cy="${y(v)}" r="2" fill="${s.color}"/><circle cx="${x(r.t)}" cy="${y(v)}" r="6" fill="transparent"><title>${esc(new Date(r.t*1000).toLocaleString('fr-CH'))} · ${esc(s.label)} : ${esc(format(v))}</title></circle>`;}}
for(const [t,anchor] of [[t0,'start'],[(t0+t1)/2,'middle'],[t1,'end']]){const date=new Date(t*1000),label=['7d','30d','1y','all'].includes(period)?date.toLocaleDateString('fr-CH',{day:'2-digit',month:'2-digit'}):date.toLocaleTimeString('fr-CH',{hour:'2-digit',minute:'2-digit'});svg+=`<text x="${x(t)}" y="${h-4}" text-anchor="${anchor}">${esc(label)}</text>`;}el.innerHTML=svg+'</svg>';}
function renderKpis(){const p=current(),online=hosts().filter(fresh).length,scope=selected==='all'?`${online}/5 machines avec données récentes`:(fresh(hosts().find(h=>h.id===selected))?'Mesure récente':'Dernière mesure connue');const cards=[['Processeur',pct(p.cpu),`${num(p.cores,0)} cœurs logiques · ${scope}`,p.cpu,'var(--cyan)','cpu'],['Mémoire vive',bytes(p.memory_used),`sur ${bytes(p.memory_total)} · ${pct(ratio(p.memory_used,p.memory_total))}`,ratio(p.memory_used,p.memory_total),'var(--purple)','memory-stick'],['Stockage monté',bytes(p.storage_used),`sur ${bytes(p.storage_total)} · volumes accessibles`,ratio(p.storage_used,p.storage_total),'var(--orange)','hard-drive'],['Réseau · réception',bytes(p.rx,true),`↑ ${bytes(p.tx,true)} en émission · interfaces physiques`,null,'var(--blue)','network']];$('#kpis').innerHTML=cards.map(([label,value,note,n,color,icon])=>`<article class="kpi" style="--accent:${color}"><div class="kpi-label"><span>${label}</span><span class="kpi-icon">${opsIcon(icon)}</span></div><div class="kpi-value">${value}</div>${meter(n,color)}<div class="kpi-note">${esc(note)}</div></article>`).join('');}
function renderProcesses(){const h=hosts().find(h=>h.id===selected);if(!h?.metrics)return;const q=$('#process-search').value.toLowerCase(),key=$('#process-sort').value;const processes=h.metrics.processes.filter(p=>p.name.toLowerCase().includes(q)||String(p.pid).includes(q)).sort((a,b)=>key==='pid'?a.pid-b.pid:(b[key]??-1)-(a[key]??-1));$('#process-count').textContent=`${h.metrics.process_count} processus au total · ${h.metrics.processes.length} principaux suivis (CPU cumulé et RAM) · arguments privés exclus`;
const states={R:'Actif',S:'En attente',D:'Attente E/S',Z:'Zombie',T:'Suspendu',I:'Inactif'};$('#processes').innerHTML=processes.map(p=>`<tr><td><strong>${esc(p.name)}</strong></td><td>${p.pid}</td><td>${esc(states[p.state]||p.state)}</td><td>${pct(p.cpu_pct)}</td><td>${bytes(p.rss_bytes)} <small>${pct(p.memory_pct)}</small></td><td>${p.threads}</td></tr>`).join('')||'<tr><td colspan="6">Aucun processus ne correspond à cette recherche.</td></tr>';}
function renderDetails(h){
 const m=h.metrics;
 if(!m){
  $('#hardware').innerHTML='<div class="info-row">En attente des premières mesures.</div>';
  for(const id of ['cores','sensors','disks','interfaces','processes'])$('#'+id).innerHTML='';
  $('#process-count').textContent='Aucune mesure';return;
 }
 const row=(a,b)=>`<div class="info-row"><span>${esc(a)}</span><span>${esc(b)}</span></div>`;
 $('#hardware').innerHTML=row('Processeur',m.cpu.model)+row('Capacité CPU',num(m.cpu.cores,0)+' cœurs logiques')+row('Charge 1 / 5 / 15 min',m.cpu.load.map(n=>num(n,2)).join(' / '))+row('En fonctionnement depuis',uptime(m.uptime_seconds))+row('RAM disponible',bytes(m.memory.available_bytes))+row('Swap utilisée / totale',bytes(m.memory.swap_used_bytes)+' / '+bytes(m.memory.swap_total_bytes));
 $('#cores').innerHTML=m.cpu.per_core.map((n,i)=>`<div class="core"><small>CŒUR ${i+1}</small>${pct(n)}</div>`).join('');
 $('#sensors').innerHTML=(m.temperatures.map(t=>row(t.name,num(t.celsius)+' °C')).join('')||row('Température','Capteur non exposé'))+(m.gpus.map(g=>row('GPU',g.name)+row('Utilisation GPU',pct(g.usage_pct))+row('VRAM',num(g.memory_used_mib)+' / '+num(g.memory_total_mib)+' Mio')+row('Puissance GPU',valid(g.power_w)?num(g.power_w)+' W':'Non mesurée')).join('')||row('GPU','Aucune mesure disponible'))+row('Puissance électrique machine','Non mesurée');
 $('#disks').innerHTML=m.filesystems.map(storageCard).join('')||'<p>Aucun volume mesurable.</p>';
 $('#interfaces').innerHTML=m.network.map(n=>`<tr><td><strong>${esc(n.name)}</strong><small>${n.physical?'Physique / principale':'Virtuelle / tunnel'}</small></td><td>${esc(n.state)}</td><td>${bytes(n.rx_bytes_per_second,true)}</td><td>${bytes(n.tx_bytes_per_second,true)}</td><td>${valid(n.speed_mbps)?num(n.speed_mbps,0)+' Mbit/s':'—'}</td><td>${num(n.rx_errors+n.tx_errors,0)} / ${num(n.rx_dropped+n.tx_dropped,0)}</td></tr>`).join('');renderProcesses();
}
function render(){const all=hosts(),online=all.filter(fresh),h=all.find(h=>h.id===selected);$('#coverage').textContent=`${online.length}/5`;$('#machines').innerHTML=all.map(h=>`<button class="machine ${selected===h.id?'active':''}" data-host="${h.id}" aria-pressed="${selected===h.id}"><span class="machine-icon" aria-hidden="true">${opsIcon(hostIcon(h.id))}</span><span class="machine-info">${esc(h.label)}<small>${h.metrics?num(h.metrics.cpu.cores,0)+' cœurs · '+bytes(h.metrics.memory.total_bytes):'Mesures en attente'}</small></span><span class="dot ${fresh(h)?'':h.status==='waiting'?'wait':'off'}" title="${fresh(h)?'Mesures récentes':'Mesures indisponibles'}"></span></button>`).join('');$('.overview').classList.toggle('active',selected==='all');$('#title').textContent=h?h.label:'Toute votre infrastructure.';$('#breadcrumb').textContent=h?h.role.toUpperCase():'VUE GLOBALE';$('#subtitle').textContent=h?'Ressources, activité et capacité de cette machine.':'Les ressources, les tendances et les points d’attention, au même endroit.';
const age=data?Math.max(0,Math.floor(Date.now()/1000-data.generated_at)):null;$('#freshness').innerHTML=`<span class="dot ${age===null?'wait':age>50?'off':''}"></span>${data?`${online.length}/5 machines · dernière collecte il y a ${age} s`:'En attente du service de mesures'}`;$('#sample-time').textContent=data?'Mise à jour '+new Date(data.generated_at*1000).toLocaleTimeString('fr-CH'):'';
renderKpis();renderHero();renderOperations();const ar=data?.archive;$('#archive-status').innerHTML=ar?`<div><strong>${num(ar.summary_count,0)}</strong><span>relevés indexés</span></div><div><strong>${ar.oldest_summary?new Date(ar.oldest_summary*1000).toLocaleDateString('fr-CH'):'—'}</strong><span>début de l’historique</span></div><div><strong>15 secondes</strong><span>archives détaillées · sans purge</span></div><div><strong>${ar.backup?.verified&&Date.now()/1000-ar.backup.checked_at<36*3600?'Vérifiée':'À vérifier'}</strong><span>${ar.backup?.offsite?.verified?'Copies NAS + VPS · '+(ar.backup.offsite.pending_archives||0)+' en attente':'sauvegarde locale des mesures'}</span></div>`:'';const alerts=[];for(const host of (h?[h]:all)){if(!fresh(host)){alerts.push(`${host.label} : ${host.metrics?'données anciennes, exclues de la synthèse':'mesures indisponibles'}`);continue;}const p=point(host);if(p.cpu>90)alerts.push(host.label+' : CPU supérieur à 90 %');if(ratio(p.memory_used,p.memory_total)>90)alerts.push(host.label+' : RAM supérieure à 90 %');for(const d of host.metrics.filesystems)if(ratio(d.used_bytes,d.total_bytes)>90)alerts.push(`${host.label} : volume ${d.mount} supérieur à 90 %`);}$('#attention').hidden=!alerts.length;$('#attention').textContent=alerts.join(' · ');
const rows=history();chart('#cpu-chart',rows,[{value:r=>r.cpu,color:'var(--cyan)',label:'CPU'}],pct,100);chart('#memory-chart',rows,[{value:r=>ratio(r.memory_used,r.memory_total),color:'var(--purple)',label:'RAM'}],pct,100);chart('#network-chart',rows,[{value:r=>r.rx,color:'var(--cyan)',label:'Réception'},{value:r=>r.tx,color:'var(--blue)',label:'Émission'}],n=>bytes(n,true));chart('#io-chart',rows,[{value:r=>r.read,color:'var(--purple)',label:'Lecture'},{value:r=>r.write,color:'var(--orange)',label:'Écriture'}],n=>bytes(n,true));
$('#history-open').disabled=!h;$('#detail-shortcuts').hidden=!h;$('#fleet-panel').hidden=!!h;$('#detail').hidden=!h;if(h)renderDetails(h);else $('#fleet').innerHTML=all.map(h=>{const p=point(h);return `<tr class="selectable" data-host="${h.id}" tabindex="0" aria-label="Ouvrir ${esc(h.label)}"><td><strong>${esc(h.label)}</strong><small>${esc(h.role)}</small></td><td><span class="status ${fresh(h)?'':'off'}"><span class="dot ${fresh(h)?'':'off'}"></span>${fresh(h)?'En ligne':'Indisponible'}</span></td><td>${pct(p.cpu)}${meter(p.cpu)}</td><td>${bytes(p.memory_used)}<small>sur ${bytes(p.memory_total)}</small></td><td>${pct(ratio(p.storage_used,p.storage_total))}${meter(ratio(p.storage_used,p.storage_total),'var(--orange)')}</td><td>${bytes(p.rx,true)}<small>↑ ${bytes(p.tx,true)}</small></td><td>${uptime(h.metrics?.uptime_seconds)}</td></tr>`;}).join('');}
async function refresh(){if(busy||historical)return;busy=true;$('#refresh').disabled=true;try{const next=await window.__TAURI__.core.invoke('infrastructure_snapshot');if(!historical)data=next;$('#notice').hidden=true;}catch(e){$('#notice').textContent=String(e);$('#notice').hidden=false;}finally{busy=false;$('#refresh').disabled=false;render();}}
document.addEventListener('click',e=>{const shortcut=e.target.closest('[data-anchor]');if(shortcut){document.getElementById(shortcut.dataset.anchor)?.scrollIntoView({block:'start',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}const host=e.target.closest('[data-host]');if(host){if(historical){historical=null;document.body.classList.remove('historical');$('#history-live').hidden=true;$('#history-label').textContent='';refresh();}selected=host.dataset.host;render();}const range=e.target.closest('[data-period]');if(range){period=range.dataset.period;document.querySelectorAll('[data-period]').forEach(b=>b.classList.toggle('active',b===range));render();}});document.addEventListener('keydown',e=>{const row=e.target.closest('tr[data-host]');if(row&&(e.key==='Enter'||e.key===' ')){e.preventDefault();selected=row.dataset.host;render();}});$('#process-search').addEventListener('input',renderProcesses);$('#process-sort').addEventListener('change',renderProcesses);$('#refresh').addEventListener('click',refresh);$('#theme').addEventListener('click',()=>{document.body.classList.toggle('light');localStorage.setItem('ops-infrastructure-theme',document.body.classList.contains('light')?'light':'dark');});if(localStorage.getItem('ops-infrastructure-theme')==='light')document.body.classList.add('light');render();refresh();setInterval(()=>{if(!document.hidden)refresh();},5000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh();});

function storageCard(d){
 const total=Math.max(0,d.total_bytes),used=Math.max(0,Math.min(total,d.used_bytes)),available=Math.max(0,Math.min(total-used,d.available_bytes)),reserved=Math.max(0,total-used-available),pc=n=>total?n/total*100:0;
 const segments=[['used','Utilisé',used],['reserved','Réservé au système',reserved],['free','Disponible',available]];
 return `<article class="storage-card"><div class="storage-head"><div class="drive-icon" aria-hidden="true">${opsIcon('hard-drive')}</div><div><h3>${esc(d.mount==='/'?'Disque système':d.mount)}</h3><small>${esc(d.device)} · ${esc(d.filesystem)}</small></div><div class="drive-total">${bytes(total)}<small>capacité du volume</small></div></div><div class="storage-caption"><strong>${bytes(used)} utilisés</strong><span>${bytes(available)} disponibles</span></div><div class="apple-storage" role="img" aria-label="${esc(d.mount)} : ${bytes(used)} utilisés, ${bytes(reserved)} réservés au système, ${bytes(available)} disponibles sur ${bytes(total)}">${segments.filter(x=>x[2]>0).map(([key,label,n])=>`<span class="segment ${key}" style="width:${pc(n)}%" title="${label} : ${bytes(n)} (${pct(pc(n))})"><span>${pc(n)>15?bytes(n):''}</span></span>`).join('')}</div><div class="storage-legend">${segments.map(([key,label,n])=>`<span><i class="${key}"></i>${label}<strong>${bytes(n)}</strong><small>${pct(pc(n))}</small></span>`).join('')}</div><div class="storage-foot"><span>Inodes libres : ${num(d.inodes_free,0)} / ${num(d.inodes_total,0)}</span><span>${pc(available)<10?'Espace disponible faible':'Capacité mesurée'}</span></div></article>`;
}

function renderOperations(){
 const op=data?.operations, services=op?.services;
 $('#service-health').innerHTML=Object.entries(services?.resources||{}).map(([id,s])=>`<div><strong>${esc(names[id]?.[0]||id)} · ${s.status==='healthy'?'Sain':'À vérifier'}</strong><span>Contrôle ${services.checked_at?new Date(services.checked_at*1000).toLocaleTimeString('fr-CH'):'—'}</span></div>`).join('')||'<p>Contrôle des services indisponible.</p>';
 const rows=op?.history||[];$('#incidents').innerHTML=rows.map(r=>`<tr><td><strong>${esc(r.title)}</strong><small>${esc(r.source)}</small></td><td>${esc(names[r.host]?.[0]||r.host)}</td><td>${esc(r.severity)}</td><td>${new Date(r.opened*1000).toLocaleString('fr-CH')}</td><td>${r.resolved?'Résolu · '+new Date(r.resolved*1000).toLocaleString('fr-CH'):'En cours'}</td></tr>`).join('')||`<tr><td colspan="5">${op?.sources?.prometheus?.status==='ok'?'Aucun incident enregistré depuis le début du suivi.':'Source d’alertes indisponible : état non confirmé.'}</td></tr>`;
}

const localDate=new Date();localDate.setMinutes(localDate.getMinutes()-localDate.getTimezoneOffset()-2);$('#history-date').value=localDate.toISOString().slice(0,19);
$('#history-open').addEventListener('click',async()=>{
 if(selected==='all')return;
 const t=Math.floor(new Date($('#history-date').value).getTime()/1000);if(!Number.isFinite(t)){ $('#history-label').textContent='Choisissez une date valide.';return; }
 $('#history-open').disabled=true;
 try{const result=await window.__TAURI__.core.invoke('infrastructure_history',{host:selected,timestamp:t});historical=result;data={...data,hosts:data.hosts.map(h=>h.id===selected?{...h,...result.host}:h)};document.body.classList.add('historical');$('#history-live').hidden=false;render();$('#history-label').textContent='Archive vérifiée · '+new Date(result.archived_at*1000).toLocaleString('fr-CH');$('#freshness').textContent='Consultation d’un relevé archivé';$('#subtitle').textContent='État enregistré à cette date, y compris les processus et volumes.';}
 catch(e){$('#history-label').textContent=String(e);}finally{$('#history-open').disabled=false;}
});
$('#history-live').addEventListener('click',()=>{historical=null;document.body.classList.remove('historical');$('#history-live').hidden=true;$('#history-label').textContent='';refresh();});

function renderHero(){const list=selected==='all'?hosts():hosts().filter(h=>h.id===selected),recent=list.filter(fresh),cores=recent.reduce((n,h)=>n+(h.metrics?.cpu.cores||0),0);$('#hero-meta').innerHTML=`<span class="hero-chip ${recent.length===list.length?'healthy':''}">${opsIcon('radio')}${recent.length}/${list.length} ${list.length===1?'machine connectée':'machines connectées'}</span><span class="hero-chip">${opsIcon('cpu')}${num(cores,0)} cœurs suivis</span><span class="hero-chip">${opsIcon('archive')}Historique permanent</span>`;}
