server {
    listen 80;
    listen [::]:80;
    server_name zulip.example.org;
    location /.well-known/acme-challenge/ { root /var/lib/ops-zulip-acme; }
    location / { return 301 https://zulip.example.org$request_uri; }
}
