[commands]
apply_updates = no
download_updates = yes
network_online_timeout = 60
random_sleep = 0
upgrade_type = security
reboot = never

[emitters]
system_name = dell-ops
emit_via = motd
emit_no_updates = no
