"""Reviewed local upgrade: native CLI pilot, account detection, shared resources.

Preserves the prior wheel environment, helper, user units and application.
No remote target or model request is generated by the installer.
"""
from pathlib import Path
import hashlib,json,os,runpy,shutil,subprocess,time
ROOT=Path('/home/ops-user/ops-control-plane')
OUT=ROOT/'artifacts/cli-continuity-2026-09-11'
RELEASE='ops-native-2026.09.11.2'
assert os.geteuid()==0
release=runpy.run_path(str(ROOT/'native_ops/release.py'))['verify'](ROOT)
assert release['release_id']==RELEASE
for name,digest in json.loads((OUT/'payload.json').read_text()).items():
 p=ROOT/name
 assert not p.is_symlink() and hashlib.sha256(p.read_bytes()).hexdigest()==digest,name
archive=Path('/var/lib/ops-native-archives')/('cli-continuity-'+str(time.time_ns()))
archive.mkdir(parents=True,mode=0o700)
def run(*args):return subprocess.run(args,check=True,capture_output=True,timeout=120)
def user(*args):return run('/usr/sbin/runuser','-u','ops-user','--','/usr/bin/env','XDG_RUNTIME_DIR=/run/user/1000','DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus',*args)
venv=Path('/opt/ops-native/venv')
shutil.copytree(venv,archive/'venv',symlinks=True)
units=Path('/home/ops-user/.config/systemd/user')
units.mkdir(parents=True,exist_ok=True);os.chown(units,1000,1000)
targets={Path('/usr/local/libexec/ops-execution-mode'):(ROOT/'native_ops/deploy/ops-execution-mode',0,0o755),
 Path('/home/ops-user/.local/lib/ops-desktop/ops-desktop'):(ROOT/'apps/ops-desktop/src-tauri/target/release/ops-desktop',1000,0o755)}
for name in ['ops-cli-pilot.service','ops-agents.slice']:
 targets[units/name]=(ROOT/'native_ops/deploy'/name,1000,0o644)
prior={}
for i,p in enumerate(targets):
 assert not p.is_symlink(),str(p)
 if p.exists():
  saved=archive/str(i);shutil.copy2(p,saved);prior[str(p)]=(str(saved),p.stat().st_uid,p.stat().st_gid,p.stat().st_mode&0o777)
 else:prior[str(p)]=None
(archive/'prior.json').write_text(json.dumps(prior))
linger=run('/usr/bin/loginctl','show-user','ops-user','-p','Linger','--value').stdout.strip()==b'yes'
try:
 pilot_enabled=user('/usr/bin/systemctl','--user','is-enabled','ops-cli-pilot.service').stdout.strip()==b'enabled'
except subprocess.CalledProcessError:pilot_enabled=False
try:
 pilot_active=user('/usr/bin/systemctl','--user','is-active','ops-cli-pilot.service').stdout.strip()==b'active'
except subprocess.CalledProcessError:pilot_active=False
(archive/'states.json').write_text(json.dumps({'linger':linger,'pilot_enabled':pilot_enabled,'pilot_active':pilot_active}))
def replace(p,source,uid,gid,mode):
 temp=p.with_name(p.name+'.cli-next')
 with temp.open('xb') as f:f.write(Path(source).read_bytes());f.flush();os.fsync(f.fileno())
 os.chown(temp,uid,gid);os.chmod(temp,mode);os.replace(temp,p)
try:
 run('/usr/bin/systemctl','stop','ops-native-capabilities.timer','ops-native-capabilities.service')
 user('/usr/bin/systemctl','--user','stop','ops-cli-pilot.service') if pilot_active else None
 run('/usr/bin/systemctl','stop','ops-native.service')
 run(str(venv/'bin/python'),'-m','pip','install','--no-index','--no-deps','--force-reinstall',str(OUT/'wheels/ops_native-0.1.9-py3-none-any.whl'))
 run(str(venv/'bin/python'),'-m','pip','check')
 for p,(source,uid,mode) in targets.items():replace(p,source,uid,uid,mode)
 code="from importlib.metadata import distribution;from pathlib import Path;p=distribution('ops-native');assert p.version=='0.1.9';assert all(p.locate_file('ops_native/'+f.name).read_bytes()==f.read_bytes() for f in Path('/home/ops-user/ops-control-plane/native_ops/ops_native').glob('*.py'))"
 run(str(venv/'bin/python'),'-I','-c',code)
 user('/usr/bin/systemctl','--user','daemon-reload')
 run('/usr/bin/loginctl','enable-linger','ops-user')
 run('/usr/bin/systemctl','start','ops-native-capabilities.service','ops-native-capabilities.timer')
 run('/usr/bin/systemctl','start','ops-native.service')
 user('/usr/bin/systemctl','--user','enable','--now','ops-cli-pilot.service')
 time.sleep(20)
 for unit in ['ops-native.service','ops-native-capabilities.timer','ops-memory.service','ops-broker.socket','openbao.service','ops-orchestrator.service']:
  run('/usr/bin/systemctl','is-active','--quiet',unit)
 user('/usr/bin/systemctl','--user','is-active','--quiet','ops-cli-pilot.service')
 accounts=json.loads(Path('/run/ops-native-cli-accounts.json').read_text())
 assert set(accounts)=={'codex','claude'} and all(type(v) is bool for v in accounts.values())
 state=json.loads(Path('/var/lib/hermes/native-ops/connector/status.json').read_text())
 assert state['status']=='running' and time.time()-state['updated_at']<30
 published=Path('/usr/local/share/ops-native/releases')/ (RELEASE+'.json')
 assert not published.exists(),'Release already published'
 published.write_bytes((ROOT/'native_ops/releases/current.json').read_bytes());published.chmod(0o444)
 result={'release':RELEASE,'status':'installed','native_version':'0.1.9','desktop_version':'0.6.4','pilot':'active','accounts':accounts,'archive':str(archive),'manifest_sha256':hashlib.sha256(published.read_bytes()).hexdigest(),'verified_at':int(time.time()),'remote_changes':False}
 proof=published.with_name(RELEASE+'-install.json');proof.write_text(json.dumps(result,indent=2)+'\n');proof.chmod(0o444)
 (archive/'result.json').write_text(json.dumps(result));print(json.dumps(result))
except BaseException:
 for args in [('stop','ops-native-capabilities.timer','ops-native-capabilities.service'),('stop','ops-native.service')]:
  subprocess.run(['/usr/bin/systemctl',*args],stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
 try:user('/usr/bin/systemctl','--user','disable','--now','ops-cli-pilot.service')
 except subprocess.CalledProcessError:pass
 if venv.exists():venv.rename(archive/'failed-venv')
 (archive/'venv').rename(venv)
 for name,info in prior.items():
  p=Path(name)
  if info is None:p.unlink(missing_ok=True)
  else:replace(p,*info)
 user('/usr/bin/systemctl','--user','daemon-reload')
 if pilot_enabled:user('/usr/bin/systemctl','--user','enable','ops-cli-pilot.service')
 if pilot_active:user('/usr/bin/systemctl','--user','start','ops-cli-pilot.service')
 if not linger:run('/usr/bin/loginctl','disable-linger','ops-user')
 run('/usr/bin/systemctl','start','ops-native.service','ops-native-capabilities.timer')
 raise
